// Mocks generated by Mockito 5.4.4 from annotations
// in movie_discovery_app/test/features/profile/data/repositories/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_discovery_app/core/error/failures.dart' as _i6;
import 'package:movie_discovery_app/features/auth/domain/entities/user_entity.dart'
    as _i5;
import 'package:movie_discovery_app/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:movie_discovery_app/features/profile/data/datasources/profile_local_data_source.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i5.UserEntity?>.empty(),
      ) as _i4.Stream<_i5.UserEntity?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity>>
      signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #signInWithEmailAndPassword,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity>>.value(
                    _FakeEither_0<_i6.Failure, _i5.UserEntity>(
              this,
              Invocation.method(
                #signInWithEmailAndPassword,
                [],
                {
                  #email: email,
                  #password: password,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity>>
      signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #signUpWithEmailAndPassword,
              [],
              {
                #email: email,
                #password: password,
                #displayName: displayName,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity>>.value(
                    _FakeEither_0<_i6.Failure, _i5.UserEntity>(
              this,
              Invocation.method(
                #signUpWithEmailAndPassword,
                [],
                {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity?>>.value(
            _FakeEither_0<_i6.Failure, _i5.UserEntity?>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.UserEntity?>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String?>> getStoredToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoredToken,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, String?>>.value(
            _FakeEither_0<_i6.Failure, String?>(
          this,
          Invocation.method(
            #getStoredToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, String?>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> storeToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #storeToken,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #clearToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i7.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLocaleCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setLocaleCode,
          [code],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
