// Mocks generated by Mockito 5.4.4 from annotations
// in movie_discovery_app/test/features/favorites/presentation/widgets/favorite_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_discovery_app/features/favorites/domain/entities/favorite_movie_entity.dart'
    as _i5;
import 'package:movie_discovery_app/features/favorites/presentation/providers/favorites_cubit.dart'
    as _i2;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoritesState_0 extends _i1.SmartFake
    implements _i2.FavoritesState {
  _FakeFavoritesState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoritesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesNotifier extends _i1.Mock implements _i2.FavoritesNotifier {
  MockFavoritesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.FavoritesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.FavoritesState>.empty(),
      ) as _i4.Stream<_i2.FavoritesState>);

  @override
  _i2.FavoritesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFavoritesState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.FavoritesState);

  @override
  set state(_i2.FavoritesState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FavoritesState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeFavoritesState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.FavoritesState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadFavoriteMovies() => (super.noSuchMethod(
        Invocation.method(
          #loadFavoriteMovies,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> addMovieToFavorites(_i5.FavoriteMovieEntity? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMovieToFavorites,
          [movie],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeFromFavorites(int? movieId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [movieId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isFavorite(int? movieId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [movieId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i5.FavoriteMovieEntity? getFavoriteMovie(int? movieId) =>
      (super.noSuchMethod(Invocation.method(
        #getFavoriteMovie,
        [movieId],
      )) as _i5.FavoriteMovieEntity?);

  @override
  _i4.Future<bool> toggleFavorite(_i5.FavoriteMovieEntity? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [movie],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  bool updateShouldNotify(
    _i2.FavoritesState? old,
    _i2.FavoritesState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.RemoveListener addListener(
    _i6.Listener<_i2.FavoritesState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i3.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
