// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-WEB-API-KEY',
    appId: '1:406930289005:web:YOUR-WEB-APP-ID',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    authDomain: 'movie-discovery-app-37e3a.firebaseapp.com',
    storageBucket: 'movie-discovery-app-37e3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY',
    appId: '1:406930289005:android:246db4af1dceee588e6a64',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    storageBucket: 'movie-discovery-app-37e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: '1:406930289005:ios:YOUR-IOS-APP-ID',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    storageBucket: 'movie-discovery-app-37e3a.appspot.com',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'com.example.movieDiscoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: '1:406930289005:ios:YOUR-MACOS-APP-ID',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    storageBucket: 'movie-discovery-app-37e3a.appspot.com',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'com.example.movieDiscoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-WINDOWS-API-KEY',
    appId: '1:406930289005:web:YOUR-WINDOWS-APP-ID',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    authDomain: 'movie-discovery-app-37e3a.firebaseapp.com',
    storageBucket: 'movie-discovery-app-37e3a.appspot.com',
  );
}
