// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6O3vBVqU5RKGuvPyV9rKoNpOAX27iDk',
    appId: '1:406930289005:web:c868e47e3ff516398e6a64',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    authDomain: 'movie-discovery-app-37e3a.firebaseapp.com',
    storageBucket: 'movie-discovery-app-37e3a.firebasestorage.app',
    measurementId: 'G-21DQ66VE41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72PMkklZ-QBvr9PmhKYcH2Pt4r3p40Tg',
    appId: '1:406930289005:android:246db4af1dceee588e6a64',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    storageBucket: 'movie-discovery-app-37e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONMSfSP9gIJ8qzyzdKEW2MB4n_2jcUcM',
    appId: '1:406930289005:ios:4eaf426500d820838e6a64',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    storageBucket: 'movie-discovery-app-37e3a.firebasestorage.app',
    iosBundleId: 'com.example.movieDiscoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONMSfSP9gIJ8qzyzdKEW2MB4n_2jcUcM',
    appId: '1:406930289005:ios:4eaf426500d820838e6a64',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    storageBucket: 'movie-discovery-app-37e3a.firebasestorage.app',
    iosBundleId: 'com.example.movieDiscoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM6O3vBVqU5RKGuvPyV9rKoNpOAX27iDk',
    appId: '1:406930289005:web:71d57b9b921c691d8e6a64',
    messagingSenderId: '406930289005',
    projectId: 'movie-discovery-app-37e3a',
    authDomain: 'movie-discovery-app-37e3a.firebaseapp.com',
    storageBucket: 'movie-discovery-app-37e3a.firebasestorage.app',
    measurementId: 'G-XLXB1KKW24',
  );
}
